name: turnkey_sdk_flutter
description: A complete SDK for building Flutter apps with Turnkey's packages
version: 0.1.0
repository: https://github.com/tkhq/dart-sdk

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  turnkey_crypto: ^0.1.1
  turnkey_encoding: ^0.1.0
  turnkey_flutter_passkey_stamper: ^0.1.0
  turnkey_api_key_stamper: ^0.1.0
  turnkey_http: ^0.1.1
  turnkey_sessions: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
