name: turnkey_flutter_demo_app
description: "A demo app using Turnkey's Flutter packages"
publish_to: "none"
repository: https://github.com/tkhq/dart-sdk

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pinput: ^5.0.1
  flutter_svg: ^1.0.3
  http: ^1.3.0
  turnkey_crypto: ^0.1.0
  turnkey_flutter_passkey_stamper: ^0.1.0
  turnkey_api_key_stamper: ^0.1.0
  turnkey_http: ^0.1.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.2
  elliptic: ^0.3.11
  flutter_dotenv: ^5.2.1
  crypto: ^3.0.6
  openid_client: ^0.4.9
  url_launcher: ^6.3.1
  uni_links: ^0.5.1
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/google.svg
    - assets/images/apple.svg
    - .env
