name: turnkey_http
description: A Dart package for making HTTP requests to the Turnkey API.
version: 0.1.0
repository: https://github.com/tkhq/dart-sdk
publish_to: https://pub.dev

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  chopper: ^8.0.4
  http: ^1.3.0
  json_annotation: ^4.9.0
  turnkey_encoding: ^0.1.0
  turnkey_api_key_stamper: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  build_test: ^2.0.0
  chopper_generator: ^8.0.4
  json_serializable: ^6.9.3
  swagger_dart_code_generator: ^3.0.1
