name: turnkey_dart_api_stamper
description: A Dart package for api stamping functionalities.
version: 0.1.0
environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  elliptic: 0.3.11
  crypto: 3.0.6
  ecdsa: 0.1.2
  turnkey_dart_http_client:
    path: ../http
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  build_test: ^2.0.0

publish_to: none # We add this temporarily, so we can use local dependencies

