name: turnkey_flutter_passkey_stamper
description: A Flutter package for passkey stamping functionalities.
version: 0.1.0
environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  crypto: 3.0.6
  passkeys: 2.4.0
  turnkey_dart_http_client:
    path: ../http
  turnkey_encoding:
    path: ../encoding
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  build_test: ^2.0.0

publish_to: none # We add this temporarily, so we can use local dependencies
